name: heroku deploy workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            RELEASE_NUMBER
        env:
          RELEASE_NUMBER: "${GITHUB_SHA}-${GITHUB_RUN_NUMBER}"
